- name: install nginx with latest version
  apt:
    name: nginx
    state: present
    autoremove: yes
    update_cache: yes
  become: yes

- name: start nginx
  service:
    name: nginx
    state: started